<!DOCTYPE HTML>
<html>
	<head>
		<?php require("templates/head.phtml") ?>
	</head>
	<body>
		<header>
			<?php require("templates/nav.phtml") ?>
		</header>
		<article>
			<form method="post">
				<?= $bank ?>
				Kolik peněz chcete převést na kreditový účet:&nbsp&nbsp&nbsp<input type="number" name="credits" value="Částka" onfocus="this.value=''" required><br />
				Souhlas s převedením <input type="checkbox" name="checkTransfer" required><br />
				<input type="submit" name="acknowledge" value="Potvrdit převod">
			</form>
			<div class="error"><?=isset($addCredit_error) ? $addCredit_error : ""?></div>
		</article>
	</body>
</html>
