<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            toto je úvodní strana ... tento školní projekt je super 
            <br>
            
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>