<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
         <?php require("templates/menu.phtml") ?>
        </header>
        <article>
            toto je úvodní strana ... tento školní projekt je na p***
            <br>
            
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>