<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
        <script type="text/javascript">
            gallery.init([
                "http://www.sportovni-stavby.cz/images/fotogalerie/2008/01-kanovice/kanovice-04.jpg", 
                "https://parkhotel-czech.eu/webroot/media/1920x1080_1507096424.2805_2215-Kurty.jpg", 
                "http://www.ceskosaske-svycarsko.cz/uploaded/odpocinkove_aktivity/tenis_nahled.jpg", 
                "http://storage.hotelmorris.cz/images/large/0e28a53a28411d939595069f7c4f5ad8.jpg"
            ]);          
        </script>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            <h1>PROVOZNÍ ØÁD<h1>
<h2>TJ Sokol Lelekovice, Skalka 292/5, Lelekovice</h2>
(dále jen TJ)
<ol type="A">
<li>OBECNÁ USTANOVENÍ</li>
<ol type="1"><li>Provozní do TJ je uvedena na vstupu do provozovny a na internetových stránkách TJ. Provozovatel si vyhrazuje právo na její zmìnu, úpravu èi omezení, napø. z dùvodu údržby, oprav nebo konání sportovních akcí. Vše oznámí nejpozdìji 3 dny pøedem.
</li>
<li>Vstupem do areálu TJ se zákazníci a návštìvníci zavazují bezvýhradnì dodržovat ustanovení Provozního øádu. Ve všech pøípadech musí uposlechnout pokynù personálu. Povinnost dodržovat ustanovení Provozního øádu vzniká už v okamžiku uèinìní objednávky na èerpání služeb.
</li>
<li>Zákazníci jsou povinni poèínat si pøi èerpání služeb takovým zpùsobem, aby neomezovali ostatní zákazníky v jejich právech. Zákazníci jsou povinni dodržovat zásady bezpeènosti provozu, hygienické a požární pøedpisy, zásady pro ochranu zdraví osob, herní pravidla a zásady bezpeèného provádìní sportovních èinností. Za všech okolností jsou povinni pøedcházet škodám na zdraví a na majetku svém i jiných osob, a to vèetnì provozovatele TJ.
</li>
<li>Zahájením èerpání služeb zákazník pøevzal na sebe plnou zodpovìdnost za dodržování ustanovení èl. 3. Nedodrží-li zákazník pøedmìtné ustanovení a dojde ke vzniku škodní události, je povinen zpùsobenou škodu nahradit.
</li>
<li>Za dìti a mládež do 18 let nesou plnou zodpovìdnost jejich rodièe. </li></ol>
<li>ZÁKAZY</li>
<ol start="6"><li>V areálu TJ je zakázáno kouøit, požívat alkoholické nápoje a omamné látky.
</li>
<li>Je zakázáno jakkoliv zasahovat do sportovištì, které je vyhrazeno pro jiné zákazníky.
</li>
<li>Poruší-li zákazník èi návštìvník TJ ustanovení Provozního øádu, personál osobu vykáže ze sportovištì. Taková osoTJ je povinna zaplatit vše, co by jinak zaplatila, pokud by k vykázání nedošlo.</li></ol>
<li>OBJEDNÁVÁNÍ SLUŽEB</li>
<ol start="9"><li>Èerpání vybraných služeb lze objednat dopøedu osobnì na recepci, telefonicky nebo on-linerezervaèním systémem.
</li>
<li>Objednávající je povinen èinit objednávky výhradnì svým jménem, rovnìž uvádí své køestní jméno a platný telefonický kontakt. Objednávající je povinen si ovìøit, zda je objednávka uèinìna v souladu s jeho pokyny. V pøípadì pochybností jsou vždy platné údaje uvedené v poèítaèi na recepci TJ a reklamace je nepøípustná.
</li>
<li>Pøijatá objednávka je vždy závazná. Závazná je i délka objednané služby. Zrušení objednávky ze strany objednávajícího lze provést osobnì nebo telefonicky, avšak nejpozdìji 24 hodin pøedem. V pøípadìzrušení objednávky 8-24 hodin pøed jejím zapoèetím je zrušení zpoplatnìno storno poplatkem ve výši 50 % ceny objednané služby, v pøípadì zrušení pozdìji než 8 hodin pøedem nebo nedostavení se na rezervaci stornopoplatkem ve výši 100 % ceny objednané služby bez nároku na náhradu objednávky.Neuhrazený storno poplatek mùže být dùvodem k odmítnutí nebo zrušení dalších objednávek. Objednávka mùže být pøijata podmíneènì, objednávající je však povinen zároveò s èerpáním objednaných služeb zaplatit požadovaný storno poplatek.
</li>
<li>Provozovatel má právo zrušit objednávku pouze existuje-li k tomu platný dùvod, a zároveò má povinnost neprodlenì informovat majitele objednávky o jejím zrušení. Rezervace není možné rušit zasláním e-mailu!</li></ol>
<li>ÈERPÁNÍ SLUŽEB</li>
<ol start="13"><li>Zákazníci èerpají služby TJ v souladu s ustanoveními Provozního øádu a podle pokynù personálu.Veškeré úhrady jsou provádìny na recepci platbou v hotovosti, pøijímanými poukázkami nebo èerpáním kreditu. Platbu kreditem je zákazník povinen oznámit pøed zaèátkem èerpání služby.
</li>
<li>Zákazníci se dostavují na objednanou službu s dostateèným pøedstihem. V opaèném pøípadì má obsluha právo nabídnout službu jinému zákazníkovi. Pro øešení zmeškaných objednávek platí ustanovení èl. 11.
</li>
<li>Zaèátek èerpání služby zaèíná rozsvícením pøíslušného osvìtlení, konec zhasnutím osvìtlení. Signalizace osvìtlení je øízena poèítaèem.
</li>
<li>Provozovatel si vyhrazuje právo zmìny èísla objednaného kurtu z provozních dùvodù.
</li>
<li>Na sportovištích se zákazníci nacházejí pouze po dobu , která jim oprávnìnì náleží. Po skonèení doby èerpání jsou zákazníci povinni ihned opustit kurty a neomezovat ostatní zákazníky v jejich právech.
</li>
<li>Vstup na kurty a do prostor vyhrazených pro služby je povolen pouze ve vhodném odìvu a obuvi.Zákazníci mohou používat pøi èerpání služeb pouze pøedepsanou sportovní obuv (èistá sálová obuv se svìtlou podrážkou), sportovní vyTJvení a doplòky neohrožující zdraví a majetek. Je zakázáno vstupovat na kurty v tenisové nebo zneèistìné obuvi. V pøípadì nesplnìní této podmínky je obsluha TJ oprávnìna takového hráèe nepustit na kurt a požadovat zaplacení objednaného kurtu.
</li>
<li>Zákazníci nevbíhají do TJdmintonové sítì a ani ji jinak nepoškozují.</li></ol>


<li>OSTATNÍ USTANOVENÍ</li>
<ol start="20"><li>Zákazník je povinen nahradit v souladu s èl. 4 škodu zpùsobenou na majetku provozovatele TJ, a to v poøizovací cenì. U pøedmìtu pùjèovny je možné, aby zákazník nahradil škodu v cenì nižší než poøizovací, a to s pøihlédnutím ke stupni døívìjšího opotøebení. O stupni opotøebení pøedmìtu rozhodne výhradnì personál TJ.
</li>
<li>Zapomenutou, odloženou, ztracenou anebo nalezenou vìc jakéhokoliv druhu je nálezce povinen odevzdat personálu TJ. Vìc bude vydána jejímu majiteli.
</li>
<li>Provozovatel TJ si vyhrazuje právo na zmìnu Provozního øádu bez pøedchozího upozornìní.</li>
</ol></ol>

        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>