<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
        <script type="text/javascript">
            gallery.init([
                "http://www.sportovni-stavby.cz/images/fotogalerie/2008/01-kanovice/kanovice-04.jpg", 
                "https://parkhotel-czech.eu/webroot/media/1920x1080_1507096424.2805_2215-Kurty.jpg", 
                "http://www.ceskosaske-svycarsko.cz/uploaded/odpocinkove_aktivity/tenis_nahled.jpg", 
                "http://storage.hotelmorris.cz/images/large/0e28a53a28411d939595069f7c4f5ad8.jpg"
            ]);          
        </script>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
        <h1>PROVOZNÍ ŘÁD</h1>
        <h2>TJ Sokol Lelekovice, Skalka 292/5, Lelekovice</h2>
        (dále jen TJ)

        <ol>
            <h3>OBECNÁ USTANOVENÍ</h3>

            <li>Provozní do TJ je uvedena na vstupu do provozovny a na internetových stránkách TJ. Provozovatel si vyhrazuje právo na její změnu, úpravu či omezení, např. z důvodu údržby, oprav nebo konání sportovních akcí. Vše oznámí nejpozději 3 dny předem.</li>
            <li>Vstupem do areálu TJ se zákazníci a návštěvníci zavazují bezvýhradně dodržovat ustanovení Provozního řádu. Ve všech případech musí uposlechnout pokynů personálu. Povinnost dodržovat ustanovení Provozního řádu vzniká už v okamžiku učinění objednávky na čerpání služeb.</li>
            <li>Zákazníci jsou povinni počínat si při čerpání služeb takovým způsobem, aby neomezovali ostatní zákazníky v jejich právech. Zákazníci jsou povinni dodržovat zásady bezpečnosti provozu, hygienické a požární předpisy, zásady pro ochranu zdraví osob, herní pravidla a zásady bezpečného provádění sportovních činností. Za všech okolností jsou povinni předcházet škodám na zdraví a na majetku svém i jiných osob, a to včetně provozovatele TJ.</li>
            <li>Zahájením čerpání služeb zákazník převzal na sebe plnou zodpovědnost za dodržování ustanovení čl. 3. Nedodrží-li zákazník předmětné ustanovení a dojde ke vzniku škodní události, je povinen způsobenou škodu nahradit.</li>
            <li>Za děti a mládež do 18 let nesou plnou zodpovědnost jejich rodiče.</li>

            <h3>ZÁKAZY</h3>

            <li>V areálu TJ je zakázáno kouřit, požívat alkoholické nápoje a omamné látky.</li>
            <li>Je zakázáno jakkoliv zasahovat do sportoviště, které je vyhrazeno pro jiné zákazníky.</li>
            <li>oruší-li zákazník či návštěvník TJ ustanovení Provozního řádu, personál osobu vykáže ze sportoviště. Taková osoTJ je povinna zaplatit vše, co by jinak zaplatila, pokud by k vykázání nedošlo.</li>

            <h3>OBJEDNÁVÁNÍ SLUŽEB</h3>
            
            <li>Čerpání vybraných služeb lze objednat dopředu osobně na recepci, telefonicky nebo on-linerezervačním systémem.</li>
            <li>Objednávající je povinen činit objednávky výhradně svým jménem, rovněž uvádí své křestní jméno a platný telefonický kontakt. Objednávající je povinen si ověřit, zda je objednávka učiněna v souladu s jeho pokyny. V případě pochybností jsou vždy platné údaje uvedené v počítači na recepci TJ a reklamace je nepřípustná.</li>
            <li>Přijatá objednávka je vždy závazná. Závazná je i délka objednané služby. Zrušení objednávky ze strany objednávajícího lze provést osobně nebo telefonicky, avšak nejpozději 24 hodin předem. V případězrušení objednávky 8-24 hodin před jejím započetím je zrušení zpoplatněno storno poplatkem ve výši 50 % ceny objednané služby, v případě zrušení později než 8 hodin předem nebo nedostavení se na rezervaci stornopoplatkem ve výši 100 % ceny objednané služby bez nároku na náhradu objednávky.Neuhrazený storno poplatek může být důvodem k odmítnutí nebo zrušení dalších objednávek. Objednávka může být přijata podmínečně, objednávající je však povinen zároveň s čerpáním objednaných služeb zaplatit požadovaný storno poplatek.</li>
            <li>Provozovatel má právo zrušit objednávku pouze existuje-li k tomu platný důvod, a zároveň má povinnost neprodleně informovat majitele objednávky o jejím zrušení. Rezervace není možné rušit zasláním e-mailu!</li>
            
            <h3>ČERPÁNÍ SLUŽEB</h3>
            
            <li>Zákazníci čerpají služby TJ v souladu s ustanoveními Provozního řádu a podle pokynů personálu.Veškeré úhrady jsou prováděny na recepci platbou v hotovosti, přijímanými poukázkami nebo čerpáním kreditu. Platbu kreditem je zákazník povinen oznámit před začátkem čerpání služby.</li>
            <li>Zákazníci se dostavují na objednanou službu s dostatečným předstihem. V opačném případě má obsluha právo nabídnout službu jinému zákazníkovi. Pro řešení zmeškaných objednávek platí ustanovení čl. 11.</li>
            <li>Začátek čerpání služby začíná rozsvícením příslušného osvětlení, konec zhasnutím osvětlení. Signalizace osvětlení je řízena počítačem.</li>
            <li>Provozovatel si vyhrazuje právo změny čísla objednaného kurtu z provozních důvodů.</li>
            <li>Na sportovištích se zákazníci nacházejí pouze po dobu , která jim oprávněně náleží. Po skončení doby čerpání jsou zákazníci povinni ihned opustit kurty a neomezovat ostatní zákazníky v jejich právech.</li>
            <li>Vstup na kurty a do prostor vyhrazených pro služby je povolen pouze ve vhodném oděvu a obuvi.Zákazníci mohou používat při čerpání služeb pouze předepsanou sportovní obuv (čistá sálová obuv se světlou podrážkou), sportovní vyTJvení a doplňky neohrožující zdraví a majetek. Je zakázáno vstupovat na kurty v tenisové nebo znečistěné obuvi. V případě nesplnění této podmínky je obsluha TJ oprávněna takového hráče nepustit na kurt a požadovat zaplacení objednaného kurtu.</li>
            <li>Zákazníci nevbíhají do TJdmintonové sítě a ani ji jinak nepoškozují.</li>

            <h3>OSTATNÍ USTANOVENÍ</h3>
            
            <li>Zákazník je povinen nahradit v souladu s čl. 4 škodu způsobenou na majetku provozovatele TJ, a to v pořizovací ceně. U předmětu půjčovny je možné, aby zákazník nahradil škodu v ceně nižší než pořizovací, a to s přihlédnutím ke stupni dřívějšího opotřebení. O stupni opotřebení předmětu rozhodne výhradně personál TJ.</li>
            <li>Zapomenutou, odloženou, ztracenou anebo nalezenou věc jakéhokoliv druhu je nálezce povinen odevzdat personálu TJ. Věc bude vydána jejímu majiteli.</li>
            <li>Provozovatel TJ si vyhrazuje právo na změnu Provozního řádu bez předchozího upozornění.</li>
        </ol>

        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>