<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
        <script type="text/javascript">
            gallery.init([
                "http://www.sportovni-stavby.cz/images/fotogalerie/2008/01-kanovice/kanovice-04.jpg", 
                "https://parkhotel-czech.eu/webroot/media/1920x1080_1507096424.2805_2215-Kurty.jpg", 
                "http://www.ceskosaske-svycarsko.cz/uploaded/odpocinkove_aktivity/tenis_nahled.jpg", 
                "http://storage.hotelmorris.cz/images/large/0e28a53a28411d939595069f7c4f5ad8.jpg"
            ]);          
        </script>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>