<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/menu.phtml") ?>
        </header>
        <article>
            <h1>Profil</h1>
            <h2><?= $user->firstName . " " . $user->lastName ?></h2>
            <div class='tabpanel' index="0">
                <div class='title'>Informace</div>
                <div class="tab">
                    <p>
                        Jméno: <span class="fname"><?= $user->firstName ?></span>
                        <br>Přijmení: <span class="lname"><?= $user->lastName ?></span>
                        <br>E-mail: <span class='email'><?= $user->email ?></span>
                        <br>Telefoní číslo: <span class='tel'><?= $user->tel ?></span>
                    </p>
                </div>
                <div class='title'>Moje rezervce</div>
                <div class="tab">
                    ...
                </div>
                <div class='title'>Nastavení</div>
                <div class="tab">
                    ...
                </div>
            </div>
            <div class='cls'></div>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>