<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            <h1>Profil</h1>
            <section>
                <h2><?= $user->firstName . " " . $user->lastName ?></h2>
                <div class='tabpanel' index="<?= $tabpanel_index ?? 0 ?>">
                    <div class='title'>Informace</div>
                    <div class="tab">
                        <p>
                            Jméno: <span class="fname"><?= $user->firstName ?></span>
                            <br>Přijmení: <span class="lname"><?= $user->lastName ?></span>
                            <br>E-mail: <span class='email'><?= $user->email ?></span>
                            <br>Telefoní číslo: <span class='tel'><?= $user->tel ?></span>
                        </p>
                    </div>
                    <div class='title'>Moje rezervce</div>
                    <div class="tab">
                        ...
                    </div>
                    <div class='title'>Nastavení účtu</div>
                    <div class="tab">
                        <form method="post">
                            <h3>avatar</h3>
                            <?= $avatars ?>
                            <input type="hidden" name="avatar_index" id="avatar_index" value="<?= $user->avatar ?>">
                            <input type="submit" name="avatar" value="Změnit avatara">
                        </form>
                        <form method="post">
                            <h3></h3>
                        </form>
                        <form method="post">
                            <h3>změna hesla</h3>
                            <table>
                                <tr>
                                    <td>Staré heslo: </td>
                                    <td><input type="password" name="old_password"></td>
                                </tr>
                                <tr>
                                    <td>Nové heslo: </td>
                                    <td><input type="password" name="new_password"></td>
                                </tr>
                                <tr>
                                    <td>Nové heslo znovu: </td>
                                    <td><input type="password" name="check_new_password"></td>
                                </tr>
                                <tr>
                                    <td><input type="submit" name="change_password" value="Změnit heslo"></td>
                                </tr>
                            </table>
                            <p><?= $passchange_error ?? "" ?></p>
                        </form>
                        <form method="post">
                            <h3>smazat účet</h3>
                            <table>
                                <tr>
                                    <td>Heslo: </td>
                                    <td><input type="password" name="password"></td>
                                </tr>
                                <tr>
                                    <td><input type="submit" name="delete_account" value="smazat účet"></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                    <div class="title">Statistiky rezervací</div>
                    <div class="tab">
                        Pracuje se na tom ... 
                    </div>
                </div>
            </section>
            <div class='cls'></div>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>