<!DOCTYPE html>
<html>
	<head>
		<?php require("templates/head.phtml") ?>
	</head>
	<body>
		<header>
			<?php require("templates/nav.phtml") ?>
		</header>
		<article>
			<h1>Profil</h1>
			<section id="profile">
				<h2><?= $user->firstName . " " . $user->lastName ?></h2>
				<div class='tabpanel' index="<?= $tabpanel_index ?? 0 ?>">
					<div class='title'>Informace</div>
					<div class="tab">
						<table id="info">
							<tr>
								<td class="nazev">Jméno: </td> 
								<td>
									<span class="fname"><?= $user->firstName ?></span>	
								</td>
							</tr>
							<tr>
								<td class="nazev">Přijmení: </td>
								<td>
									<span class="lname"><?= $user->lastName ?></span>
								</td>
							</tr>
							<tr>
								<td class="nazev">E-mail: </td>
								<td>
									<span class="email"><?= $user->email ?></span>
								</td>
							</tr>
							<tr>
								<td class="nazev">Telefoní číslo: </td>
								<td>
									<span class="tel"><?= $user->tel ?></span>
								</td>
							</tr>
						</table>
					</div>
					<div class='title'>Moje rezervce</div>
					<div class="tab">
						<div class="myres"><?= $reservations ?></div>
					</div>
					<div class='title'>Nastavení účtu</div>
					<div class="tab">
						<form method="post">
							<h3>avatar</h3>
							<?= $avatars ?>
							<input type="hidden" name="avatar_index" id="avatar_index" value="<?= $user->avatar ?>">
							<input class="right" type="submit" name="avatar" value="Změnit avatara">
							<div class="cls"></div>
						</form>
						<form method="post">
							<h3>změna hesla</h3>
							<table>
								<tr>
									<td>Staré heslo: </td>
									<td><input type="password" name="old_password"></td>
								</tr>
								<tr>
									<td>Nové heslo: </td>
									<td><input type="password" name="new_password"></td>
								</tr>
								<tr>
									<td>Nové heslo znovu: </td>
									<td><input type="password" name="check_new_password"></td>
								</tr>
								<tr class="transparent">
									<td colspan="2"><input class="right" type="submit" name="change_password" value="Změnit heslo"></td>
								</tr>
							</table>
							<p class="error"><?= $passchange_error ?? "" ?></p>
						</form>
						<form method="post">
							<h3>smazat účet</h3>
							<table>
								<tr>
									<td>Heslo: </td>
									<td><input type="password" name="password"></td>
								</tr>
								<tr class="transparent">
									<td colspan="2"><input class="right" type="submit" name="delete_account" value="smazat účet"></td>
								</tr>
							</table>
							<p class="error"><?= $delete_account_error ?? "" ?></p>
						</form>
					</div>
					<div class="title">Statistiky rezervací</div>
					<div class="tab">
						Pracuje se na tom ... 
					</div>
				</div>
			</section>
			<div class='cls'></div>
		</article>
		<footer>
			<?= $footer ?>
		</footer>
	</body>
</html>
