<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/menu.phtml") ?>
        </header>
        <article>
            <div id="reservation"> 
                <!-- tabulka s rezervacemi -->
                <div class='left'> 
                    <div id="table" class="tabpanel" index="0"><?= $allreservation; ?></div>
                    <div class='cls'></div>
                </div>
                <!-- kalendář -->
                <div class='right'>
                    <div id="calendar"><?= $calendar ?></div>
                    <div class='cls'></div>
                </div>
                <div class='cls'></div>
            </div>
                        
            <!-- vytváření rezervací -->
            <?php 
                if ($user->isLogged()) require("templates/reservation.phtml"); 
                else echo "Pro rezervaci se musíte <a href='signin'>přihlásit</a>. ";
            ?>

            <div class='cls'></div>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>