<!DOCTYPE html>
<html>
	<head>
		<?php require("templates/head.phtml") ?>
	</head>
	<body>
		<header>
			<?php require("templates/nav.phtml") ?>
		</header>
		<article>
			<form method="post">
				<table id="signup" class="form">
					<thead>
						<tr><th colspan="2"><h2>Registrace</h2></th></tr>
					</thead>
					<tbody>
						<tr>
							<th>Email: </th>
							<td><input onkeyup="checking_email(this)" type="email" name="email" required value="<?= isset($_POST["email"]) ? $_POST["email"] : '' ?>"></td>
						</tr>
						<tr>
							<th>Heslo: </th>
							<td><input onkeyup="checking_password(this)" type="password" name="password" required></td>
						</tr>
						<tr>
							<th>Opakujte heslo: </th>
							<td><input onkeyup="checking_password_check(this)" type="password" name="password_check" required></td>
						</tr>
						<tr>
							<th>Jméno: </th>
							<td><input type="text" name="fname" required value="<?= isset($_POST["fname"]) ? $_POST["fname"] : '' ?>"></td>
						</tr>
						<tr>
							<th>Přijmení: </th>
							<td><input type="text" name="lname" required value="<?= isset($_POST["lname"]) ? $_POST["lname"] : '' ?>"></td>
						</tr>
						<tr>
							<th>Telefoní číslo: </th>
							<td><input type="text" name="tel" required value="<?= isset($_POST["tel"]) ? $_POST["tel"] : '' ?>"></td>
						</tr>
						<tr>
							<th>Antispam (aktuální rok): </th>
							<td><input type="text" name="year" required></td>
						</tr>
						<tr>
							<td colspan="2"><input class="right" type="submit" name="signup" value="Zaregistrovat" onclick="check_year()"></td>
						</tr>
					</tbody>
				</table>
			</form>
			<div class='error'><?= $signup_error ?? "" ?></div>
		</article>
		<footer>
			<?= $footer ?>
		</footer>
	</body>
</html>
