<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            <?php 
                require("templates/sUsers.phtml") /* : require("templates/sEvents.phtml") */
            ?>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>