<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
        </header>
        <article>
            <?php 
                require("templates/navSprava.phtml");
                //ty události se budou dát dělat na kartě rezervace ... (je tam GUI pro dny a hodiny) ... už je to z části hotoví
                //require("templates/sEvents.phtml"); proto už existuje šablona event.phml :D
                /* ($choice) ? */ require("templates/sUsers.phtml") /* : require("templates/sEvents.phtml") */
                //require("templates/sUsers.phtml"); 
            ?>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>