<!DOCTYPE html>
<html>
    <head>
        <?php require("templates/head.phtml") ?>
    </head>
    <body>
        <header>
            <?php require("templates/nav.phtml") ?>
            <h1>Správa</h1>
        </header>
        <article>
        <?php require("templates/navSprava.phtml") ?>
        <?php require("templates/sEvents.phtml") ?>
        <?php require("templates/sUsers.phtml") ?>
        </article>
        <footer>
            <?= $footer ?>
        </footer>
    </body>
</html>