<div class='title'>Rezervace</div>
<div class='tab'>
    <form method="post">
        <table>
            <tr>
                <td>Od: </td>
                <td><input type="datetime" name="from" value="<?= $_POST["from"] ?? "" ?>"></td>
            </tr>
            <tr>
                <td>Délka rezervace: </td>
                <td><input type="number" id="duration" name="duration" value="<?= $_POST["duration"] ?? "1" ?>"></td>
            </tr>
            <tr>
                <td>Opakovat: </td>
            </tr>
            <tr>
                <td>Rezervovat: </td>
                <td class="places"></td>
            </tr>
            <tr>
                <td>Rezervovat pro počet lidí: </tr>
            </tr>
            <tr>
                <td><input type="submit" name="nreservation" value="rezervovat"></td>
            </tr>
        </table>
    </form>
</div>