<div class='title'>Rezervace</div>
<div class='tab'>
    <form method="post">
        <table>
            <tr>
                <td>Od: </td>
                <td><input type="datetime" name="from" value="<?= $_POST["from"] ?? "" ?>"></td>
            </tr>
            <tr>
                <td>Délka rezervace: </td>
                <td><input type="number" id="duration" name="duration" min="1" value="<?= $_POST["duration"] ?? "1" ?>"></td>
            </tr>
            <tr>
                <td>Opakovat: </td>
                <td><?= $repeat ?></td>
                <td><?= $repeat_combobox->get() ?></td>
                <td><input type="number" name="count" value="1" min="1"></td>
            </tr>
            <tr>
                <td>Rezervovat: </td>
                <td class="places"></td>
            </tr>
            <tr>
                <td>Rezervovat pro počet lidí: </td>
                <td><input type="number" name="nPeople" value="1" min="1"></td>
            </tr>
            <tr>
                <td><input type="submit" name="reservation" value="rezervovat"></td>
            </tr>
        </table>
    </form>
</div>