

<!-- ukáže možnost pøidání usera -->
<button id="e_u" onclick="ahoj()">Vytvoøit nového uživatele</button><br /><br />
<!-- má vzít hodnoty a udìlat nového usera-->
<p id="pas"></p>
<table border="4" id="tableCreate" style="display:'none';">
   <tr>
        <th>Jméno</th>
        <td><input id="name" value='Jméno' onfocus="this.value=''"></td>
    </tr>
    <tr>
        <th>Pøijmení</th>
        <td><input id="surname" value="Pøíjmení" onfocus="this.value=''"></td>
    </tr>
    <tr>
        <th>Heslo</th>
        <td><input id="password" value="Heslo" onfocus="this.value=''"></td>
    </tr>
    <tr>
        <th>Email</th>
        <td><input id="email" value="Email" onfocus="this.value=''"></td>
    </tr>
    <tr>
        <th>Telefon</th>
        <td><input id="telNumber" value="Telefonní èíslo" onfocus="this.value=''"></td>
    </tr>
    <tr>
        <th>Právo</th>
        <td><input id="level" value="ID práv" onfocus="this.value=''"></td>
   </tr>
    <tr>
        <td><button onclick="saveTable()" style="width:125px;" id="pridat">OK</button></td>
        <td><button onclick="hideTable()" style="width:125px;" id="zrusit">Zrušit</button></td>
    </tr>
</table>
<br /><br />

Vymazat uživatele:&nbsp&nbsp&nbsp<input name="znicit" value="ID" onfocus="this.value=''" size="5">
<br />
<button onClick="ChooseTable::delUser" id="delUser">Výmaz</button>
<br /><br />
<table border="2" id="tableData">
    <th>Jméno</th>
    <th>Pøijmení</th>
    <th>Email</th>
    <th>Telefon</th>
    <th>Právo</th>
    <th>ID</th>   
</table>
